<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/common_inertia.xacro" />

    <xacro:macro name="base_xacro" params="radius length">

        <!-- gazebo 色彩管理 -->
        <gazebo reference="base_link">
            <material>Gazebo/CeilingTiled</material>
        </gazebo>

        <!-- 基础固定点，可以视为机器人在环境中的位置参考 -->
        <link name="base_footprint" />

        <!-- 将基础固定点连接到机器人主体 -->
        <joint name="base_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
        </joint>

        <!-- 机器人主体链接 -->
        <link name="base_link">
            <visual>
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>                    
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>                    
                </material>
            </collision>
            
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}" />
        </link>
    </xacro:macro>
    
</robot>
